travis:
  secure:
    BINSTAR_TOKEN: wd86r2f7W4YcHFhHYcKNzacV/OM1SV0w2sIgZbIavtN6LchYoYr7HV8T2i3DJN1wCVA0MP91ivh00W1BDS7g6tNhppURhZ6WUMk5ZXpwh8J433D2S/fxKNMoOdMd8r35OEm/2yzhU1PxzvPqj8jWpU35vI/4WLoJ/LmOxKmEEEN2zzIUqwzAK9zTrgjUWKU7DVm6ysU6RXWjh07j47jzOratOaahjFQVu8Xap93JRP4930DVrsi8Dg5ZVZkUygV5MY08lTiGCqeJVCl302+69+ZCfTmUzjnoU1Dieb//V/Gg2M8VhULhNSDm+22QXDupXgDKkatXebsxBuOMBmIAMf5FsUhnjPZ1xyoMsFz73eIMzfqDIuSIP6nOgOpbxPRAk7Lw1JqxExAlLBKQSQtso8k63GadRbuB14Y6FAbopQ2cqaZV1muSd5Lpbn3B4BKEgZiqY0ErqhQ5tNSD4FAon3KDHrF9VbbxPPmyWcAv4Z9boJBQM8BPzE5BfIF6eJdwOD49usFxW9J4d7yD0Wz1MiOAxNx3omBpRkAlq0rnVzV50TuhP4bXFBH9E+kZNPcBmf/09+sf1gRwreUmXL7GjV57WwB8aV0Qc0I1+KwWzRjyfhmz4707pRtYK7gG4a9CIA9yaBmvV73JmlVm40aOQIoOEmLZwzn09XaFvZ59zd8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
