travis:
  secure:
    BINSTAR_TOKEN: Lxsm2qo4bp7CAxUQz7VcxQOqr4OTgqsUouJIbzCl0Gi3LfkhboRJWOBdCn2fFwmY7UH5aLPCcrGAyvWmWgPtE/5h5xQsSgT1SuMpBd3v8s+B59w+jiINEN8mIp7O6T8Z1nGgWVbl5a19NLjUNskgpPhlDv/+Wzwfv22q1C210QnnnVnPebgoZE3FZThRjxXRv4oj3kynmGbUmIHreI1n7q6l3GHWXs+J19XgQmtrasbJ4T4hpFbShY9dKMfC3pupN8U2aX0p7E8AQUtld2+ycBXRTPtLUxwbibj564E7HLbnEr79y6Im8i4sSNhSaHQDrrcfL7kkN3iqy9xpsEYquGhRxDleLs7+uott02IjGTugfd5lgsP4P195MrVYDYEops4H+q+1iOguR2Xb8efBh0CZUhi27mxfaZE5gywEvsOlf1qQOdw4oLpBZklMZPmn/wwyHSQNFfxUm9cXgGsdV8CsnDcsqoQFkGhHCcOkiWGHA+Nx956p0C4Imkie/FQPvJ/pXle9WVS+y39UgPtU9CVyckADDfWzWYAhSMy6eWeiwWRtxY0/ZnDW1BfoO0giFs3mpmEvruOvFCCXBNh+FHaEwlaL3LleZOFeSREGHeZah5mznQvQCm1pPgJk71o3wRrTKy1UvTUPID0vNk/xictZGNTz4LKwxYyIvZr6DR8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
