travis:
  secure:
    BINSTAR_TOKEN: OrG5Sty76Tc/dS/HFGroldBxCYpCHtnA+CkgnPoTmHinAfa6WWRVTy9EgSL6Qf3W83QDBRCaQ5+kVCiIqgI0CqusWNiNNNXY9Bae4iN6QU/6ehZdXeDXkhwn4H2kj0oxueMLgLfNr+wptOoZNAEAZxkO9gMiVhMN/EQOikn3oJ0IuZ2iFqWyrgs3qcNVJZyw7yryuRoZ8jMYwHhYg18ESMbV7MfHC0wnvkMrnjup51sjQInKl+/cnuFceOY2i758rWE8gXF+56awnlSIxBcZvnYXrLAWkfjwTBfYUDWvKXv3PU5ZI9tvRu6EvUydGRwJ18KUr2bzGNeWB0JF6f4oxhWPlgBdVUjkF/3vaXTlZhoLmErlnVyys5cJkP9ICkqwwwpvtPC+OTo9HJ6POY0QwnzW//DMeeUFFbLnpbYTllA1y1iskg/Ip+ZukQZ8h+anNx24zwHUUzRa2U3mw2UlnT/qjEwPDTQQx5uBQtLE3Gfk1fcZB8cmAF4XPYYbSMsop3YZUmxXWxtdnYZ1QMWarjKWaIOTzJX24TPhQfCRU7SaeEoHdx1sQWpi6UExIFLN3MlSi5IGaqr4YoSqh0jmS27CDP5xDM1J2AACQxF8/fUGFJYaIz0GPdDJNtdxY6ukoCN6XqJYK8nUUzNLb+uV8OajwXTukmuRpiEPpnpWMg8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
