travis:
  secure:
    BINSTAR_TOKEN: N8Lb2EnvQFXeIwJml716oilAU6BMi91iSk+SKr8mqPqq5FfHKKY8p95BmdryDz0mB91MAbOM20WPvfl7ajQ2DtE1mfaLHJkQvEX6c0ZiyqTZEW0BcA4UyDDfxJlf6L5y7tP5Nwrkbh8otyScmZb7ZBSOAmJxw8mj05p0twWKgYO2fIQTeNiEUdEGySrj4l8JtTX/HiMSO8yqmRV07cp139YayeW6JDbUa6TARxbhO0wfDFCXfIqoUJ4AiT8ibHUsqim6+8MqX8L1rZP3QPGuJ47zr4oA3SL7WJc2MMVMMSS+5fYAb8LvuIzFt9lgdpWCiqfiM7UjsokMgsfce+/MJrHJ1lsjhWD8kngSCKUplwweHyN6edW7qMNHug6aBIhuG4eqZaknB8MMXb0hwanG7LLmdQcfPkwf+h/u0iPmV2I36N0qyLV1ByfCEPytF/ZlBtr7uEKOc2A7QwcOZQSlrW7HVzGTFvN1C3mclbGAgoE1qfs0Kb4eFZtPj8QHTcqd0jORlujCIIQA+TT657bJHbneSvFxc4/RcZDFonPAUll279XfzRxMlN4K1KPZQQXHOdiRRbtbwCbB1B9mOCYwUs55j+L32pShJ+pKeVe3LxAi++w8U1Mp3UhUat7KiZxYS/eJRA74Zyvbm1PoHKVx3lDUlBT0CqjIad+Z5fseevQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
